
---

- name: Configuring Route Redistribution 
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - answerfile_deploy.yml
  
  tasks:

  - name: Configure Redistribution "{{ esg1.name }}"
    nsx_redistribution:
      ospf_state: present
      bgp_state: absent
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      edge_name: "{{ esg1.name }}"
      prefixes:
        - {name: "{{ prefix1.name }}", network: "{{ prefix1.network }}" }
      rules:
      #redistribute summary route
        - {learner: 'ospf', priority: 0, static: 'true', connected: 'false', bgp: 'false', ospf: 'false', prefix: "{{ prefix1.name }}", action: 'permit'}
    register: redist
    tags: redist

  - name: Configure Redistribution "{{ esg2.name }}"
    nsx_redistribution:
      ospf_state: present
      bgp_state: absent
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      edge_name: "{{ esg2.name }}"
      prefixes:
        - {name: "{{ prefix1.name }}", network: "{{ prefix1.network }}" }
      rules:
      #Redistribute summary route 
        - {learner: 'ospf', priority: 0, static: 'true', connected: 'false', bgp: 'false', ospf: 'false', prefix: "{{ prefix1.name }}", action: 'permit'}
    register: redist
    tags: redist

  - name: Configure OSPF Redistribution "{{ dlr.name }}"
    nsx_redistribution:
      ospf_state: present
      bgp_state: absent
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      edge_name: "{{ dlr.name }}"
      rules:
       #Redistributes connected routes - uncomment if needed
       #- {learner: 'ospf', priority: 0, static: false, connected: true, bgp: false, ospf: false, action: 'permit'}
    register: redist
    tags: redist

