
---


- name: Preparing Cluster "{{ targetClusters.cluster2.clusterName }}" for VXLAN (Installing VIBs)
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - answerfile_deploy.yml

  tasks:

  - name: gather moid for vxlan cluster2
    vcenter_gather_moids:
      hostname: "{{ vcHostname }}"
      username: "{{ vcUser }}"
      password: "{{ vcPassword }}"
      datacenter_name: "{{ nsxmgr.datacenter }}"
      cluster_name: "{{ targetClusters.cluster2.clusterName }}"
      validate_certs: False
    register: gather_moids_cl
    tags: create_vxlan_cluster

  - name: Cluster1 preparation
    nsx_cluster_prep:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      cluster_moid: "{{ gather_moids_cl.object_id }}"
    register: cluster_prep

#  - debug: var=cluster_prep
