
---

- name: Configuring NSX Manager Backup
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - answerfile_deploy.yml

  tasks:

  - name: Configuring FTP settings
    nsx_backup:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      name: 'markiemark'
      password: 'password'
      transfer_protocol: 'FTP'      #choices = ['FTP,'SFTP']
      ip_addr: '192.168.56.78'
      port: '21'
      backup_directory: 'test/dir/path'
      file_name_prefix: 'mynsx-'
      pass_phrase: 'pass'
      #backup_frequency:
    register: ftp_settings

  - debug: var=ftp_settings
