#Single site deployment with two (2) ECMP ESGs

---

- import_playbook: deploy_nsxova.yml
- import_playbook: deploy_registration.yml
- import_playbook: deploy_license.yml
- import_playbook: deploy_ippools.yml
- import_playbook: deploy_controllers.yml 
- import_playbook: deploy_clusterprep_c1.yml
- import_playbook: deploy_clusterprep_c2.yml
- import_playbook: deploy_vxlanprep_c1.yml
- import_playbook: deploy_vxlanprep_c2.yml
- import_playbook: deploy_segmentpool.yml
- import_playbook: deploy_transportzone.yml
- import_playbook: deploy_logicalswitch.yml
- import_playbook: deploy_dlr.yml
- import_playbook: deploy_esg1.yml
- import_playbook: deploy_esg2.yml
- import_playbook: deploy_ospf.yml
- import_playbook: deploy_route_redist.yml
